## Step1: Data Raw

* Transaction: Giao dịch

* Trong giao dịch thì sẽ có các item

In [6]:
ls_trans =[
["Apple", "Beer", "Rice", "Chicken"],
["Apple", "Beer", "Rice"],
["Apple", "Beer"],
["Apple", "Pear"],
["Milk", "Beer", "Rice", "Chicken"],
["Milk", "Beer", "Rice"],
["Milk", "Beer"],
["Milk", "Pear"]
]
print(ls_trans)
# Transaction: Giao

[['Apple', 'Beer', 'Rice', 'Chicken'], ['Apple', 'Beer', 'Rice'], ['Apple', 'Beer'], ['Apple', 'Pear'], ['Milk', 'Beer', 'Rice', 'Chicken'], ['Milk', 'Beer', 'Rice'], ['Milk', 'Beer'], ['Milk', 'Pear']]

## Step 2: Xử lý Data Raw -> bảng Transaction

* Sử dụng thư viện TransactionEncoder

In [7]:
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd
model_transaction = TransactionEncoder()
ls_trans = model_transaction.fit_transform(ls_trans)
df_trans = pd.DataFrame(ls_trans,columns = model_transaction.columns_)
df_trans.replace(['True','False'],[1,0], inplace = True)
df_trans

   Apple   Beer  Chicken   Milk   Pear   Rice
0   True   True     True  False  False   True
1   True   True    False  False  False   True
2   True   True    False  False  False  False
3   True  False    False  False   True  False
4  False   True     True   True  False   True
5  False   True    False   True  False   True
6  False   True    False   True  False  False
7  False  False    False   True   True  False

## Step3: Using Apriori to count Support

In [14]:
from mlxtend.frequent_patterns import apriori
df_support = apriori(df_trans,min_support = 0.01,use_colnames=True)
df_support = df_support.sort_values("support",ascending=False)
df_support

    support                      itemsets
1     0.750                        (Beer)
0     0.500                       (Apple)
3     0.500                        (Milk)
5     0.500                        (Rice)
12    0.500                  (Rice, Beer)
11    0.375                  (Beer, Milk)
6     0.375                 (Beer, Apple)
21    0.250         (Rice, Chicken, Beer)
16    0.250                  (Rice, Milk)
22    0.250            (Rice, Beer, Milk)
14    0.250               (Rice, Chicken)
9     0.250                 (Rice, Apple)
10    0.250               (Chicken, Beer)
4     0.250                        (Pear)
2     0.250                     (Chicken)
18    0.250           (Rice, Beer, Apple)
20    0.125         (Chicken, Beer, Milk)
23    0.125         (Rice, Chicken, Milk)
24    0.125  (Rice, Chicken, Beer, Apple)
13    0.125               (Chicken, Milk)
19    0.125        (Rice, Chicken, Apple)
17    0.125        (Chicken, Beer, Apple)
15    0.125                  (Pear, Milk)
8     0.125                 (Pear, Apple)
7     0.125              (Chicken, Apple)
25    0.125   (Rice, Chicken, Beer, Milk)

## Step 4: Using Association Rule to calculate Lift, Support, Confidence

=> Association rule chỉ hỗ trợ mn đưa ra quyết định thôi

In [16]:
from mlxtend.frequent_patterns import association_rules
df_association = association_rules(df_support,metric='lift',min_threshold=1)
# antecedents: A (xuất hiện trước)
# consequents: B (Xuất hiện sau) A-> B
df_association.sort_values(["support","confidence","lift"],ascending=False)

   antecedents             consequents  ...  conviction  zhangs_metric
0       (Rice)                  (Beer)  ...         inf            0.5
1       (Beer)                  (Rice)  ...        1.50            1.0
3       (Milk)                  (Beer)  ...        1.00            0.0
5      (Apple)                  (Beer)  ...        1.00            0.0
2       (Beer)                  (Milk)  ...        1.00            0.0
..         ...                     ...  ...         ...            ...
91      (Milk)   (Rice, Chicken, Beer)  ...        1.00            0.0
36      (Beer)         (Chicken, Milk)  ...        1.05            1.0
56      (Beer)  (Rice, Chicken, Apple)  ...        1.05            1.0
70      (Beer)        (Chicken, Apple)  ...        1.05            1.0
90      (Beer)   (Rice, Chicken, Milk)  ...        1.05            1.0

[92 rows x 10 columns]

### ACTION
- Upsell
- Cross sell
- Notification
- Combo